services:
  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword

  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8501:8501
      - 8502:8502
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:8085"
      - "7077:7077"
    networks:
      - airflow

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - airflow

  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - airflow

volumes:
  minio-data:
    driver: local
