services:
  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword

  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8501:8501
      - 8502:8502

  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  duckdb:
    build:
      context: ./duckdb
      dockerfile: Dockerfile
    container_name: duckdb
    volumes:
      - duckdb:/duckdb
      - ./DW:/DW
    depends_on:
      - minio
    networks:
      - airflow
      - metabase
    command: [ "tail", "-f", "/dev/null" ]

volumes:
  minio-data:
    driver: local
  duckdb:
    driver: local
